### ISSUE TITLE
New 申请

### ISSUE THREAD

**Issue by luthor-li** [zoo-js/zoo#10]
### 😀 申请人 Applicant

- GitHub: luthor

### 🌏 领养宠物 Adopt pets

1. unicorn
2. 
3.

**Comment by luthor-li** [comment]
pets

**Comment by xrkffgg** [comment]
最近有事，一周后会进行邀请，见谅。

**Comment by xrkffgg** [comment]
Invited. Please check your email. 😄

**Comment by HuaRin** [comment]
Invitation expired. User did not accept this invite for 7 days.

Closed. If have any questions, free to leave a comment below.
