### ISSUE TITLE
[Feature] 增加水豚

### ISSUE THREAD

**Issue by laike9m** [zoo-js/zoo#110]
### 🥰 需求描述 Description of Requirement

您好，请问可以添加水豚(capybara)么？

### 🧐 解决方案 Solution

N/A

### 🚑 其他信息 Other information

N/A

**Comment by xrkffgg** [comment]
安排 ing……

**Comment by laike9m** [comment]
这张图就不错
https://twitter.com/nao_capybara/status/1333179562914549760?s=19

**Comment by xrkffgg** [comment]
https://github.com/capybara-love

看下这个

**Comment by xrkffgg** [comment]
目前的图标有点太不清晰，我再找找。风格上还是偏向于卡通。

**Comment by laike9m** [comment]
恩恩风格没问题。不过我个人还是希望能用正面照或者大头照的感觉。当然如果你觉得不想改那我也OK
