### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by ajinwu** [zoo-js/zoo#117]
### 😀 申请人 Applicant

GitHub Email: ajin_w@163.com

### 🌏 领养萌物 Adopt

1. cat
2. mermaid
3. butterfly
4. dolphin
5. monkey

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
Github Email 

你把模板的 Email 删了？
