### ISSUE TITLE
New 申请

### ISSUE THREAD

**Issue by andy7076** [zoo-js/zoo#12]
### 😀 申请人 Applicant

- GitHub: andy7076

### 🌏 领养宠物 Adopt pets

1. pig
2. monkey
3. giraffe

**Comment by xrkffgg** [comment]
最近有事，一周后会进行邀请，见谅。

**Comment by xrkffgg** [comment]
Invited. Please check your email.

**Comment by HuaRin** [comment]
Invitation expired. User did not accept this invite for 7 days.

Closed. If have any questions, free to leave a comment below.
