### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by fish-8** [zoo-js/zoo#127]
### 😀 申请人 Applicant

GitHub Email: xxx@xx.xx

### 🌏 领养萌物 Adopt

1. xx
2.
3.
4.
5.

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
what，这都可以？
好像是没检验申请的类别，但应该会报错的

**Comment by xrkffgg** [comment]
@fish-8 我修复了下，你新开个 issue 吧。建议使用在线预览的形式。
