### ISSUE TITLE
New 申请

### ISSUE THREAD

**Issue by HerSoul** [zoo-js/zoo#13]
### 😀 申请人 Applicant

- GitHub: herSoul

### 🌏 领养宠物 Adopt pets

1. unicorn
2. honeybee
3. snake

**Comment by xrkffgg** [comment]
近期有事，晚几天邀请，见谅。

**Comment by xrkffgg** [comment]
Invited. Please check your email.

**Comment by HuaRin** [comment]
Invitation expired. User did not accept this invite for 7 days.

Closed. If have any questions, free to leave a comment below.
