### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by CN-Sean** [zoo-js/zoo#149]
### 😀 申请人 Applicant

GitHub Email: wenwu.shao@qq.com

### 🌏 领养萌物 Adopt

1. tortoise
2. whale
3. sloth
4. sheep
5. pikachu

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
奇怪，第一次怎么校验失败了
