### ISSUE TITLE
[BUG] C的图片是C#

### ISSUE THREAD

**Issue by fruit-in** [zoo-js/zoo#153]
### 🐛 Bug 描述 Bug description
这是C#的图片，列表里的名称是C
![](https://avatars0.githubusercontent.com/u/75880060?s=200&v=4)

### 🏞 期望结果 Desired result
换图或者换名称

**Comment by fruit-in** [comment]
@xrkffgg 是 **#**，不是++，没改对

**Comment by xrkffgg** [comment]
👌
