### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by CaoDonghui123** [zoo-js/zoo#164]
### 😀 申请人 Applicant

GitHub Email: caodonghui_123@163.com

### 🌏 领养萌物 Adopt

1. Cool Game
2. bug
3. go

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
你好，go 调整了下，已重新邀请。
