### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by XeryYue** [zoo-js/zoo#176]
### 😀 申请人 XeryYue

GitHub Email: 81237533@qq.com

### 🌏 领养萌物 Adopt

1.  react
2.  vue
3.
4.
5.

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by ajuner** [comment]
格式有误，修改一下噢~

**Comment by xrkffgg** [comment]
@ajuner pets 格式的提示 没说空格，你加一下呗~

**Comment by XeryYue** [comment]
好的。。我记得我敲了空格 @xrkffgg

**Comment by xrkffgg** [comment]
@XeryYue 你的邮箱多加了个空格。。。检验没过

可以直接用过在线网站筛选，格式自动的。

**Comment by XeryYue** [comment]
好吧。。 @xrkffgg
