### ISSUE TITLE
[Feature] New function

### ISSUE THREAD

**Issue by Neteraxe** [zoo-js/zoo#182]
### 🥰 需求描述 Description of Requirement

想添加一本和书有关的（因为有一个成为图书管理员的梦想）。
其实是图书馆。
（有时不是很想做工程，想做一些数学？深度学习？（算法？）方面的文档。）

### 🧐 解决方案 Solution

https://www.svgrepo.com/svg/277499/library-book
我觉得这张图比较图书馆。
如果有更好的也可以。

### 🚑 其他信息 Other information

感谢作者。

**Comment by Neteraxe** [comment]
如果fork害怕整乱代码结构
这张也不错
https://www.svgrepo.com/svg/181739/library-book

**Comment by xrkffgg** [comment]
https://github.com/online-books 这个如何?

**Comment by Neteraxe** [comment]
总觉得和图书馆有点区别……

**Comment by Neteraxe** [comment]
但是如果多个工程都是书确实有点重，但是我认为online的书和实体书还是有区别的，但也可能是我个人看法。

**Comment by Neteraxe** [comment]
虽然也是online，但是图书馆是有一种莫名的安心的感觉。那种感觉很难说。

**Comment by xrkffgg** [comment]
https://github.com/library-home ?

**Comment by Neteraxe** [comment]
就是一种莫名其妙的感觉（不知道怎么形容）。和通常做的工程有一定不同
