### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by OldPanda** [zoo-js/zoo#186]
### 😀 申请人 Applicant

GitHub Email: me@old-panda.com

### 🌏 领养萌物 Adopt

1. panda

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
@ajuner 邮箱正则不支持 这个邮箱，我给先注释了。。。现在有这种邮箱吗？

**Comment by OldPanda** [comment]
>现在有这种邮箱吗？

当然啦，这是我个人域名邮箱
