### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by iChunyu** [zoo-js/zoo#232]
### 😀 申请人 Applicant

GitHub Email: chunyu2018@foxmail.com

### 🌏 领养萌物 Adopt

1. cat
2. smiley

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by iChunyu** [comment]
不好意思，[Issue #231](https://github.com/zoo-js/zoo/issues/231) 填错了邮箱地址（衰）。:cry:

**Comment by ajuner** [comment]
可以啦

**Comment by xrkffgg** [comment]
@ajuner 直接加个 auto 标签就行，不用 reopen 也不用移除标签

**Comment by iChunyu** [comment]
非常感谢！！！

**Comment by ajuner** [comment]
> @ajuner 直接加个 auto 标签就行，不用 reopen 也不用移除标签

了解
