### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by LinzhouLi** [zoo-js/zoo#260]
### 😀 申请人 Applicant

GitHub Email: LinzhouLi@outlook.com

### 🌏 领养萌物 Adopt

1. vue
2. mario
3. dog
4. injury emoji
5. rainbow

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by LinzhouLi** [comment]
没有收到邀请

**Comment by xrkffgg** [comment]
邮件对吗？

**Comment by LinzhouLi** [comment]
不好意思，收到邮件了，刚才没看到。多谢
