### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by xhemj** [zoo-js/zoo#27]
### 😀 申请人 Applicant

- GitHub:xhemj

### 🌏 领养宠物 Adopt pets

1.snake
2.dinosaur
3.canary

### 🌈 Tip

- 完成领养后，建议自行关闭 issue。
- [如何展示？](https://github.com/zoo-js/welcome/blob/master/how-to-show.md)
- [我可以做什么？](https://github.com/zoo-js/welcome/blob/master/what-we-can.md)

**Comment by xrkffgg** [comment]
Emm，手动的竟然会移除 labels

**Comment by xrkffgg** [comment]
Invited. Please check your email.
