### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by vaecebyZ** [zoo-js/zoo#283]
### 😀 申请人 Applicant

GitHub Email: vaeceby2@qq.com

### 🌏 领养萌物 Adopt

1. squirrel

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by vaecebyZ** [comment]
### 😀 申请人 Applicant

GitHub Email: vaeceby2@qq.com




### 🌏 领养萌物 Adopt

1.acorn




### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
@vaecebyZ 你想申请哪个？

**Comment by vaecebyZ** [comment]
> @vaecebyZ 你想申请哪个？
acorn

**Comment by xrkffgg** [comment]
还有么、、、机会一次

**Comment by vaecebyZ** [comment]
> @vaecebyZ 你想申请哪个？

我没仔细看以为一次只能拿一个。

**Comment by xrkffgg** [comment]
一次可以选 5 个

**Comment by vaecebyZ** [comment]
> 还有么、、、机会一次

emmm不行。

**Comment by xrkffgg** [comment]
https://github.com/zoo-js/zoo/issues/284  

修改这个，最多支持选 5 个，选好后，说一声。

**Comment by vaecebyZ** [comment]
> #284
> 
> 修改这个，最多支持选 5 个，选好后，说一声。

OK
