### ISSUE TITLE
领养

### ISSUE THREAD

**Issue by zhadongmin** [zoo-js/zoo#3]
### 😀 申请人 Applicant

- GitHub: zhadongmin

### 🌏 领养宠物 Adopt pets

1. whale
2. 
3.

**Comment by xrkffgg** [comment]
```diff
- zhadongming
+ zhadongmin
```
😀

Invited, please check.

**Comment by xrkffgg** [comment]
邀请是发送到邮箱的，收到了吧

**Comment by zhadongmin** [comment]
进了
