### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by kilingzhang** [zoo-js/zoo#311]
### 😀 申请人 Applicant

GitHub Email: ores.nimbus.0u@icloud.com

### 🌏 领养萌物 Adopt

1. panda
2. peach
3. happy emoji

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by ajuner** [comment]
还有其他的想选嘛  可以手动帮你再邀请下

**Comment by ajuner** [comment]
如果还有其他的可以跟这个panda放一起选  但是原则上一共不能超过5个噢

**Comment by ajuner** [comment]
如果没有其他想选的了直接回复下  我在这个issue上操作了

**Comment by kilingzhang** [comment]
1. panda
2. peach
3. happy emoji

辛苦
