### ISSUE TITLE
[Feature] 既然有 rebot ，希望也能添加一个 GUNDAM 2333

### ISSUE THREAD

**Issue by yuchiXiong** [zoo-js/zoo#315]
### 🥰 需求描述 Description of Requirement
希望可以在 Life 类中添加 GUNDAM - 高达 

### 🚑 其他信息 Other information
找到了一些可以参考的图例hhh
![image](https://user-images.githubusercontent.com/48373109/141601745-daa47461-1397-4a73-bb40-899fe2d81833.png)

**Comment by ajuner** [comment]
感觉这张图跟现有风格有点点差别

**Comment by yuchiXiong** [comment]
> 感觉这张图跟现有风格有点点差别

确实是hhh这个图是百度来的

**Comment by xrkffgg** [comment]
最近比较忙，过段时间再搞
