### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by wendellhu95** [zoo-js/zoo#32]
### 😀 申请人 Applicant

- GitHub: wendellhu95

### 🌏 领养宠物 Adopt pets

1. unicorn
2. 
3. 
4. 
5. 

### 🌈 Tip

- After completing the adoption, it is recommended to close the issue yourself. 完成领养后，建议自行关闭 issue。
- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/master/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/master/what-we-can.md)

**Comment by xrkffgg** [comment]
Invited. Please check your email.
