### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by fanyebo** [zoo-js/zoo#323]
### 😀 申请人 Applicant

GitHub Email: fanyebo2015@sina.com

### 🌏 领养萌物 Adopt

1. panda

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by fanyebo** [comment]
未收到邮件,可以重新申请吗?

**Comment by ajuner** [comment]
再看看

**Comment by fanyebo** [comment]
收到了,谢谢!
