### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by war408705279** [zoo-js/zoo#36]
### 😀 申请人 Applicant

- GitHub: war408705279

### 🌏 领养宠物 Adopt pets

1. totoro
2. sheep
3. monkey
4. panda
5. pikachu

### 🌈 Tip

- After completing the adoption, it is recommended to close the issue yourself. 完成领养后，建议自行关闭 issue。
- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
Invited. Please check your email.

**Comment by war408705279** [comment]
> Invited. Please check your email.

joined, thx~
