### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by eryajf** [zoo-js/zoo#367]
### 😀 申请人 Applicant

GitHub Email: Linuxlql@163.com

### 🌏 领养萌物 Adopt

1. dragon
2. panda
3. swan

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by eryajf** [comment]
dragon
panda
swan

**Comment by ajuner** [comment]
最多申请5个噢 🍬
