### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by BigCoke233** [zoo-js/zoo#42]
### 😀 申请人 Applicant

- GitHub: BigCoke233

### 🌏 领养宠物 Adopt pets

1. koala
2. alpaca
3. shark
4. pikachu
5. whale

### 🌈 Tip

- After completing the adoption, it is recommended to close the issue yourself. 完成领养后，建议自行关闭 issue。
- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
Invited. Please check your email.
