### ISSUE TITLE
[New] 申请  test auto

### ISSUE THREAD

**Issue by xrkffgg** [zoo-js/zoo#48]
### 😀 申请人 Applicant

GitHub Email: xrkffgg@gamil.com

### 🌏 领养宠物 Adopt pets

1. ant
2. pig
3.
4.
5.

### 🌈 Tip

- After completing the adoption, it is recommended to close the issue yourself. 完成领养后，建议自行关闭 issue。
- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
xrkffgg@gmail.com
ant
pig

**Comment by HuaRin** [comment]
🎉 Hi, @. Already invited, please check your email.

**Comment by HuaRin** [comment]
🎉 Hi, @xxx. Already invited, please check your email.

**Comment by Kermit-Xuan** [comment]
不是有个 issue 的 helper 么？让用户在那填入信息不行么？

**Comment by xrkffgg** [comment]
![Uploading image.png…]()

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/98194170-b2f6c800-1f59-11eb-8181-919b049d8977.png)
