### ISSUE TITLE
New 申请

### ISSUE THREAD

**Issue by BovineBoy** [zoo-js/zoo#5]
### 😀 申请人 Applicant

- GitHub: zuoning777

### 🌏 领养宠物 Adopt pets

1. dog
2. 
3.

**Comment by xrkffgg** [comment]
?? 自己关了？ 要领吗？

**Comment by BovineBoy** [comment]
> ?? 自己关了？ 要领吗？

啊？ 这个是真的宠物吗 还是什么

**Comment by xrkffgg** [comment]
不是真的，就是 GitHub  个人页 Organizations 展示的

**Comment by BovineBoy** [comment]
> 不是真的，就是 GitHub 个人页 Organizations 展示的

来一只谢谢

**Comment by xrkffgg** [comment]
Invited, please check your email.

**Comment by xrkffgg** [comment]
😂😂 邀请的是你填写的，不是你这个号哟
