### ISSUE TITLE
[QA] 使用zoo-issue-help打开没有动物列表

### ISSUE THREAD

**Issue by ajuner** [zoo-js/zoo#61]
### 问题描述

打开如下图
![image](https://user-images.githubusercontent.com/53512912/98630471-35b2c500-2356-11eb-84ef-d3ec2d828476.png)

### 原因

DNS污染，raw.githubusercontent.com无法链接

### 解决方案

# Windows

通过IPAddress.com首页,输入raw.githubusercontent.com查询到真实IP地址
199.232.68.133
打开C:\Windows\System32\drivers\etc\hosts文件
添加 以下内容并保存即可恢复
199.232.68.133 raw.githubusercontent.com

# Mac

打开终端（Terminal），默认位置在 启动台 --> 其它 --> 终端
在终端中，输入以下命令，使用vim修改hosts文件（会要求输入计算机密码）：sudo vi /etc/hosts
确保输入法为英文模式，按一下键盘上的 i 键
使用方向键，将光标移动至文本尾部，然后再文件尾部添加以下文本：199.232.68.133 raw.githubusercontent.com
按一下esc，然后输入 :wq! ,然后回车

# Linux 系统

和Mac下操作基本一致

转载：
https://www.cnblogs.com/zuoanfengxi/p/12724698.html
https://www.jianshu.com/p/bbd79e0444ea

**Comment by xrkffgg** [comment]
解决方案可以把 mac 的也列上

**Comment by KaiOrange** [comment]
找个梯子。。。
