### ISSUE TITLE
[BUG] 无法正常收到项目邀请

### ISSUE THREAD

**Issue by Levix** [zoo-js/zoo#72]
### 🐛 Bug 描述 Bug description

无法正常收到项目邀请。

### 🏞 期望结果 Desired result

能正常收到项目邀请。

### 🚑 其他信息 Other information

无

**Comment by ajuner** [comment]
检查一下邮箱是对的吧 levix.dev@makeblock.com

**Comment by ajuner** [comment]
试试看用你登录github的邮箱申请一次

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/98912483-24f28280-2501-11eb-8d79-7e78d2414671.png)

**Comment by xrkffgg** [comment]
邮箱对吗？

**Comment by Levix** [comment]
> 邮箱对吗？

我的锅，敲错邮箱了。

**Comment by xrkffgg** [comment]
新开个 issue 申请吧
