### ISSUE TITLE
[New] 申请

### ISSUE THREAD

**Issue by zcong1993** [zoo-js/zoo#75]
### 😀 申请人 Applicant

GitHub Email: zhangcong1992@gmail.com

### 🌏 领养宠物 Adopt pets

1. chick
2. unicorn
3. sheep

### 🌈 Tip

- [How to show? 如何展示？](https://github.com/zoo-js/welcome/blob/main/how-to-show.md)
- [What we can? 我可以做什么？](https://github.com/zoo-js/welcome/blob/main/what-we-can.md)

**Comment by xrkffgg** [comment]
@zcong1993 有兴趣加入 zoo-js ?

**Comment by zcong1993** [comment]
@xrkffgg 可以

**Comment by xrkffgg** [comment]
有钉钉吗

**Comment by zcong1993** [comment]
@xrkffgg 抱歉才看到, zcong1993
